### PR TITLE
Remove test-related structs from src/model.

### PR DESCRIPTION
**Pull request by guidorice**
Thanks for making this crate, although I have not really used it yet, it def. could come in handy.
I noticed there seems to be some leftover test-related structs (Dog and Flea) in model.rs.

### CODE REVIEW

**Comment by guidorice** [comment]
Oops I missed the contribution guidelines but I seem them now. This PR probably does not affect the changelog.

**Comment by JadedEvan** [comment]
@guidorice just to keep things tidy - would you be open to rebasing your changes to modify the commit message per the contribution guidelines? I'd think `refactor` is probably the most appropriate tag for your work here ([conventional docs](https://github.com/conventional-changelog/conventional-changelog/blob/a5505865ff3dd710cf757f50530e73ef0ca641da/conventions/angular.md#type))

**Comment by guidorice** [comment]
Sure, will do! 👍

**Comment by guidorice** [comment]
@JadedEvan please let me know if the PR looks OK now. Thanks

**Comment by JadedEvan** [comment]
Looking good @guidorice  - thanks for accommodating the changes! We've yanked codecov on this project since it wasn't adding much value, we can ignore those failures on this latest CI build.

**Pull request merged**
